//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicTable
    {
        public string IdNumber { get; set; }
        public string SongName { get; set; }
        public string Album { get; set; }
        public string Band { get; set; }
        public string Author { get; set; }
        public string ReleaseDate { get; set; }
        public string Length { get; set; }
    }
}
